// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idcard.proto

package book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyResult int32

const (
	VerifyResult_Unused            VerifyResult = 0
	VerifyResult_Match             VerifyResult = 1
	VerifyResult_Mismatch          VerifyResult = 2
	VerifyResult_NonstandardName   VerifyResult = 3
	VerifyResult_NonstandardNumber VerifyResult = 4
	VerifyResult_NonexistentNumber VerifyResult = 5
)

var VerifyResult_name = map[int32]string{
	0: "Unused",
	1: "Match",
	2: "Mismatch",
	3: "NonstandardName",
	4: "NonstandardNumber",
	5: "NonexistentNumber",
}

var VerifyResult_value = map[string]int32{
	"Unused":            0,
	"Match":             1,
	"Mismatch":          2,
	"NonstandardName":   3,
	"NonstandardNumber": 4,
	"NonexistentNumber": 5,
}

func (x VerifyResult) String() string {
	return proto.EnumName(VerifyResult_name, int32(x))
}

func (VerifyResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c0457ec9a92161a4, []int{0}
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0457ec9a92161a4, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0457ec9a92161a4, []int{1}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

type VerifyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	UserIP               string   `protobuf:"bytes,3,opt,name=UserIP,proto3" json:"UserIP,omitempty"`
	UserID               int64    `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Scene                string   `protobuf:"bytes,5,opt,name=Scene,proto3" json:"Scene,omitempty"`
	AppID                string   `protobuf:"bytes,11,opt,name=AppID,proto3" json:"AppID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0457ec9a92161a4, []int{2}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VerifyRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *VerifyRequest) GetUserIP() string {
	if m != nil {
		return m.UserIP
	}
	return ""
}

func (m *VerifyRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *VerifyRequest) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *VerifyRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

type VerifyReply struct {
	Result               VerifyResult `protobuf:"varint,1,opt,name=Result,proto3,enum=idcard.VerifyResult" json:"Result,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Number               string       `protobuf:"bytes,3,opt,name=Number,proto3" json:"Number,omitempty"`
	IDInfoKey            string       `protobuf:"bytes,4,opt,name=IDInfoKey,proto3" json:"IDInfoKey,omitempty"`
	AppID                string       `protobuf:"bytes,11,opt,name=AppID,proto3" json:"AppID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VerifyReply) Reset()         { *m = VerifyReply{} }
func (m *VerifyReply) String() string { return proto.CompactTextString(m) }
func (*VerifyReply) ProtoMessage()    {}
func (*VerifyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0457ec9a92161a4, []int{3}
}

func (m *VerifyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReply.Unmarshal(m, b)
}
func (m *VerifyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReply.Marshal(b, m, deterministic)
}
func (m *VerifyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReply.Merge(m, src)
}
func (m *VerifyReply) XXX_Size() int {
	return xxx_messageInfo_VerifyReply.Size(m)
}
func (m *VerifyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReply.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReply proto.InternalMessageInfo

func (m *VerifyReply) GetResult() VerifyResult {
	if m != nil {
		return m.Result
	}
	return VerifyResult_Unused
}

func (m *VerifyReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VerifyReply) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *VerifyReply) GetIDInfoKey() string {
	if m != nil {
		return m.IDInfoKey
	}
	return ""
}

func (m *VerifyReply) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

type QueryIDInfoRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	AppID                string   `protobuf:"bytes,11,opt,name=AppID,proto3" json:"AppID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryIDInfoRequest) Reset()         { *m = QueryIDInfoRequest{} }
func (m *QueryIDInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIDInfoRequest) ProtoMessage()    {}
func (*QueryIDInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0457ec9a92161a4, []int{4}
}

func (m *QueryIDInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryIDInfoRequest.Unmarshal(m, b)
}
func (m *QueryIDInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryIDInfoRequest.Marshal(b, m, deterministic)
}
func (m *QueryIDInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIDInfoRequest.Merge(m, src)
}
func (m *QueryIDInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QueryIDInfoRequest.Size(m)
}
func (m *QueryIDInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIDInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIDInfoRequest proto.InternalMessageInfo

func (m *QueryIDInfoRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *QueryIDInfoRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

type QueryIDInfoReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	AppID                string   `protobuf:"bytes,11,opt,name=AppID,proto3" json:"AppID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryIDInfoReply) Reset()         { *m = QueryIDInfoReply{} }
func (m *QueryIDInfoReply) String() string { return proto.CompactTextString(m) }
func (*QueryIDInfoReply) ProtoMessage()    {}
func (*QueryIDInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0457ec9a92161a4, []int{5}
}

func (m *QueryIDInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryIDInfoReply.Unmarshal(m, b)
}
func (m *QueryIDInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryIDInfoReply.Marshal(b, m, deterministic)
}
func (m *QueryIDInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIDInfoReply.Merge(m, src)
}
func (m *QueryIDInfoReply) XXX_Size() int {
	return xxx_messageInfo_QueryIDInfoReply.Size(m)
}
func (m *QueryIDInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIDInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIDInfoReply proto.InternalMessageInfo

func (m *QueryIDInfoReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueryIDInfoReply) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *QueryIDInfoReply) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func init() {
	proto.RegisterEnum("idcard.VerifyResult", VerifyResult_name, VerifyResult_value)
	proto.RegisterType((*PingRequest)(nil), "idcard.PingRequest")
	proto.RegisterType((*PingReply)(nil), "idcard.PingReply")
	proto.RegisterType((*VerifyRequest)(nil), "idcard.VerifyRequest")
	proto.RegisterType((*VerifyReply)(nil), "idcard.VerifyReply")
	proto.RegisterType((*QueryIDInfoRequest)(nil), "idcard.QueryIDInfoRequest")
	proto.RegisterType((*QueryIDInfoReply)(nil), "idcard.QueryIDInfoReply")
}

func init() { proto.RegisterFile("idcard.proto", fileDescriptor_c0457ec9a92161a4) }

var fileDescriptor_c0457ec9a92161a4 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x9b, 0x8d, 0x37, 0x4a, 0x26, 0xfb, 0xc7, 0xf5, 0xb6, 0x28, 0x5a, 0x71, 0xa8, 0xf6,
	0x54, 0x21, 0x54, 0xa1, 0x22, 0x71, 0x47, 0x84, 0x43, 0x16, 0x75, 0x55, 0xbc, 0x2d, 0xf7, 0x74,
	0x33, 0x2d, 0x91, 0x36, 0x4e, 0x70, 0x1c, 0x44, 0x1e, 0x83, 0xc7, 0xe1, 0x3d, 0x38, 0xf0, 0x38,
	0xc8, 0x76, 0x52, 0x76, 0x4b, 0x2f, 0x48, 0xf4, 0xe6, 0xef, 0xe7, 0x71, 0x3c, 0xf3, 0x79, 0x26,
	0x30, 0xca, 0xb3, 0x4d, 0x2a, 0xb3, 0xb3, 0x4a, 0x96, 0xaa, 0x64, 0x9e, 0x55, 0x8b, 0x31, 0x84,
	0x97, 0xb9, 0xb8, 0xe3, 0xf8, 0xa5, 0xc1, 0x5a, 0x2d, 0x42, 0x08, 0xac, 0xac, 0xb6, 0xed, 0xe2,
	0xa7, 0x03, 0xe3, 0x4f, 0x28, 0xf3, 0xdb, 0xb6, 0xdb, 0x66, 0x0c, 0xc8, 0x2a, 0x2d, 0x30, 0x72,
	0x4e, 0x9c, 0xd3, 0x80, 0x9b, 0x35, 0x7b, 0x06, 0xde, 0xaa, 0x29, 0x6e, 0x50, 0x46, 0x03, 0x43,
	0x3b, 0xa5, 0xf9, 0x75, 0x8d, 0x32, 0xb9, 0x8c, 0x5c, 0xcb, 0xad, 0xba, 0xe7, 0x71, 0x44, 0x4e,
	0x9c, 0x53, 0xb7, 0xe3, 0x31, 0x3b, 0x82, 0xe1, 0x7a, 0x83, 0x02, 0xa3, 0xa1, 0x09, 0xb7, 0x42,
	0xd3, 0xb7, 0x55, 0x95, 0xc4, 0x51, 0x68, 0xa9, 0x11, 0x4b, 0xe2, 0x8f, 0xe8, 0x78, 0x49, 0xfc,
	0x31, 0x9d, 0x2c, 0x89, 0x3f, 0xa1, 0xd3, 0x25, 0xf1, 0xa7, 0x94, 0xf2, 0xe0, 0x2a, 0x2f, 0x70,
	0xad, 0xd2, 0xa2, 0xe2, 0xfe, 0xaa, 0x14, 0x1b, 0x5c, 0x2b, 0xc9, 0xfd, 0x75, 0x7e, 0x27, 0xae,
	0xda, 0x0a, 0x39, 0xd1, 0xab, 0xc5, 0x2f, 0x07, 0xc2, 0xbe, 0xac, 0x6a, 0xdb, 0xb2, 0x97, 0xe0,
	0x71, 0xac, 0x9b, 0xad, 0x32, 0x65, 0x4d, 0xce, 0x8f, 0xce, 0x3a, 0xa7, 0xfa, 0x20, 0xbd, 0xc7,
	0xbb, 0x98, 0x7b, 0x0b, 0x06, 0x8f, 0x5a, 0xe0, 0xee, 0x59, 0xf0, 0x1c, 0x82, 0x24, 0x4e, 0xc4,
	0x6d, 0xf9, 0x01, 0x5b, 0x53, 0x6d, 0xc0, 0xff, 0x80, 0xa7, 0x28, 0xad, 0x05, 0xf6, 0xb1, 0x41,
	0xd9, 0xda, 0x4b, 0xfa, 0x57, 0xa3, 0xe0, 0xea, 0x04, 0xec, 0xa3, 0xb9, 0x4f, 0x74, 0xf5, 0x77,
	0x07, 0xe8, 0xde, 0xdd, 0xda, 0xda, 0x7f, 0xe9, 0x97, 0xff, 0x9f, 0xd3, 0x8b, 0xaf, 0x30, 0xda,
	0x7d, 0x43, 0x06, 0xe0, 0x5d, 0x8b, 0xa6, 0xc6, 0x8c, 0x1e, 0xb0, 0x00, 0x86, 0x17, 0xa9, 0xda,
	0x7c, 0xa6, 0x0e, 0x1b, 0x81, 0x7f, 0x91, 0xd7, 0x85, 0x51, 0x03, 0x36, 0x83, 0xe9, 0xaa, 0x14,
	0xb5, 0x4a, 0x45, 0x96, 0xca, 0x4c, 0xa7, 0x4c, 0x5d, 0x76, 0x0c, 0x87, 0xbb, 0xd0, 0x64, 0x4c,
	0x49, 0x87, 0xf1, 0x5b, 0x5e, 0x2b, 0x14, 0xaa, 0xc3, 0xc3, 0xf3, 0x1f, 0x0e, 0x78, 0x49, 0xfc,
	0x2e, 0x95, 0x19, 0x7b, 0x05, 0x44, 0x0f, 0x14, 0x9b, 0xf5, 0x4d, 0xb5, 0x33, 0x6d, 0xf3, 0xc3,
	0x7d, 0xa8, 0x67, 0xee, 0x80, 0xbd, 0x01, 0xcf, 0x26, 0xcd, 0x8e, 0x1f, 0x36, 0xa2, 0x3d, 0x35,
	0x7b, 0x88, 0xed, 0xb9, 0xf7, 0x10, 0xee, 0xf8, 0xcf, 0xe6, 0x7d, 0xd4, 0xdf, 0x0d, 0x31, 0x8f,
	0x1e, 0xdd, 0x33, 0x9f, 0xb9, 0xf1, 0xcc, 0xff, 0xe1, 0xf5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x46, 0x56, 0x4c, 0xa4, 0x2f, 0x04, 0x00, 0x00,
}
