// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequest_Corpus int32

const (
	CreateOrderRequest_UNIVERSAL CreateOrderRequest_Corpus = 0
	CreateOrderRequest_WEB       CreateOrderRequest_Corpus = 1
	CreateOrderRequest_IMAGES    CreateOrderRequest_Corpus = 2
	CreateOrderRequest_LOCAL     CreateOrderRequest_Corpus = 3
	CreateOrderRequest_NEWS      CreateOrderRequest_Corpus = 4
	CreateOrderRequest_PRODUCTS  CreateOrderRequest_Corpus = 5
	CreateOrderRequest_VIDEO     CreateOrderRequest_Corpus = 6
)

var CreateOrderRequest_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}

var CreateOrderRequest_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x CreateOrderRequest_Corpus) String() string {
	return proto.EnumName(CreateOrderRequest_Corpus_name, int32(x))
}

func (CreateOrderRequest_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3, 0}
}

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SearchOrderRequest struct {
	Query                string    `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32     `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32     `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	Person               []*Person `protobuf:"bytes,4,rep,name=person,proto3" json:"person,omitempty"`
	Snippets             []string  `protobuf:"bytes,5,rep,name=snippets,proto3" json:"snippets,omitempty"`
	Num                  float64   `protobuf:"fixed64,6,opt,name=num,proto3" json:"num,omitempty"`
	Price                float32   `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Status               bool      `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchOrderRequest) Reset()         { *m = SearchOrderRequest{} }
func (m *SearchOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SearchOrderRequest) ProtoMessage()    {}
func (*SearchOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *SearchOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchOrderRequest.Unmarshal(m, b)
}
func (m *SearchOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchOrderRequest.Marshal(b, m, deterministic)
}
func (m *SearchOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchOrderRequest.Merge(m, src)
}
func (m *SearchOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SearchOrderRequest.Size(m)
}
func (m *SearchOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchOrderRequest proto.InternalMessageInfo

func (m *SearchOrderRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchOrderRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchOrderRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *SearchOrderRequest) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *SearchOrderRequest) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

func (m *SearchOrderRequest) GetNum() float64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *SearchOrderRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SearchOrderRequest) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// --------创建订单------------
type OneofMessage struct {
	// Types that are valid to be assigned to TestOneof:
	//	*OneofMessage_Name
	//	*OneofMessage_Value
	TestOneof            isOneofMessage_TestOneof `protobuf_oneof:"test_oneof"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OneofMessage) Reset()         { *m = OneofMessage{} }
func (m *OneofMessage) String() string { return proto.CompactTextString(m) }
func (*OneofMessage) ProtoMessage()    {}
func (*OneofMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *OneofMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofMessage.Unmarshal(m, b)
}
func (m *OneofMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofMessage.Marshal(b, m, deterministic)
}
func (m *OneofMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofMessage.Merge(m, src)
}
func (m *OneofMessage) XXX_Size() int {
	return xxx_messageInfo_OneofMessage.Size(m)
}
func (m *OneofMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OneofMessage proto.InternalMessageInfo

type isOneofMessage_TestOneof interface {
	isOneofMessage_TestOneof()
}

type OneofMessage_Name struct {
	Name string `protobuf:"bytes,4,opt,name=name,proto3,oneof"`
}

type OneofMessage_Value struct {
	Value int64 `protobuf:"varint,9,opt,name=value,proto3,oneof"`
}

func (*OneofMessage_Name) isOneofMessage_TestOneof() {}

func (*OneofMessage_Value) isOneofMessage_TestOneof() {}

func (m *OneofMessage) GetTestOneof() isOneofMessage_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *OneofMessage) GetName() string {
	if x, ok := m.GetTestOneof().(*OneofMessage_Name); ok {
		return x.Name
	}
	return ""
}

func (m *OneofMessage) GetValue() int64 {
	if x, ok := m.GetTestOneof().(*OneofMessage_Value); ok {
		return x.Value
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OneofMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OneofMessage_Name)(nil),
		(*OneofMessage_Value)(nil),
	}
}

type CreateOrderRequest struct {
	Om                   *OneofMessage             `protobuf:"bytes,1,opt,name=om,proto3" json:"om,omitempty"`
	MpValues             map[int64]string          `protobuf:"bytes,2,rep,name=mp_values,json=mpValues,proto3" json:"mp_values,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Corpus               CreateOrderRequest_Corpus `protobuf:"varint,4,opt,name=corpus,proto3,enum=CreateOrderRequest_Corpus" json:"corpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetOm() *OneofMessage {
	if m != nil {
		return m.Om
	}
	return nil
}

func (m *CreateOrderRequest) GetMpValues() map[int64]string {
	if m != nil {
		return m.MpValues
	}
	return nil
}

func (m *CreateOrderRequest) GetCorpus() CreateOrderRequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return CreateOrderRequest_UNIVERSAL
}

type CreateOrderReply struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderReply) Reset()         { *m = CreateOrderReply{} }
func (m *CreateOrderReply) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReply) ProtoMessage()    {}
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *CreateOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReply.Unmarshal(m, b)
}
func (m *CreateOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReply.Marshal(b, m, deterministic)
}
func (m *CreateOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReply.Merge(m, src)
}
func (m *CreateOrderReply) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReply.Size(m)
}
func (m *CreateOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReply proto.InternalMessageInfo

func (m *CreateOrderReply) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func init() {
	proto.RegisterEnum("CreateOrderRequest_Corpus", CreateOrderRequest_Corpus_name, CreateOrderRequest_Corpus_value)
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterType((*SearchOrderRequest)(nil), "SearchOrderRequest")
	proto.RegisterType((*OneofMessage)(nil), "OneofMessage")
	proto.RegisterType((*CreateOrderRequest)(nil), "CreateOrderRequest")
	proto.RegisterMapType((map[int64]string)(nil), "CreateOrderRequest.MpValuesEntry")
	proto.RegisterType((*CreateOrderReply)(nil), "CreateOrderReply")
}

func init() {
	proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077)
}

var fileDescriptor_cd01338c35d87077 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0xdd, 0x49, 0x36, 0xd9, 0xe4, 0x6e, 0xb7, 0xc6, 0xb1, 0x94, 0xb8, 0x20, 0x8d, 0x79, 0x90,
	0xbc, 0x18, 0x64, 0x05, 0x11, 0x05, 0xa1, 0xdd, 0x06, 0x5b, 0x69, 0x77, 0x97, 0x89, 0x6d, 0xc1,
	0x97, 0x90, 0x76, 0xaf, 0x75, 0x31, 0xc9, 0xa4, 0x33, 0x89, 0xb0, 0x7f, 0xe7, 0x27, 0xf9, 0x09,
	0x32, 0x93, 0x20, 0x56, 0xfb, 0x76, 0xcf, 0xd9, 0xb3, 0x67, 0xce, 0x3d, 0x33, 0x81, 0x31, 0x17,
	0x6b, 0x14, 0x71, 0x2d, 0x78, 0xc3, 0xc3, 0x23, 0xb0, 0x57, 0x28, 0x24, 0xaf, 0x28, 0x85, 0x61,
	0x95, 0x97, 0xe8, 0x93, 0x80, 0x44, 0x2e, 0xd3, 0x33, 0xdd, 0x05, 0x63, 0xb3, 0xf6, 0x8d, 0x80,
	0x44, 0x16, 0x33, 0x36, 0x6b, 0xba, 0x07, 0x16, 0x96, 0xf9, 0xa6, 0xf0, 0x4d, 0x2d, 0xea, 0x40,
	0xf8, 0x8b, 0x00, 0x4d, 0x31, 0x17, 0x37, 0xdf, 0x96, 0xca, 0x99, 0xe1, 0x5d, 0x8b, 0xb2, 0x51,
	0xe2, 0xbb, 0x16, 0xc5, 0xb6, 0x77, 0xec, 0x00, 0x3d, 0x80, 0x71, 0x9d, 0xdf, 0x62, 0x56, 0xb5,
	0xe5, 0x35, 0x8a, 0xde, 0x1b, 0x14, 0xb5, 0xd0, 0x0c, 0x7d, 0x01, 0x8f, 0x04, 0xca, 0xb6, 0x68,
	0xb2, 0x1a, 0x45, 0xa6, 0x7e, 0xd0, 0xa7, 0x59, 0x6c, 0xd2, 0xd1, 0x2b, 0x14, 0xab, 0xfc, 0x16,
	0xe9, 0x01, 0xd8, 0xb5, 0x4e, 0xee, 0x0f, 0x03, 0x33, 0x1a, 0xcf, 0x46, 0x71, 0xb7, 0x08, 0xeb,
	0x69, 0x3a, 0x05, 0x47, 0x56, 0x9b, 0xba, 0xc6, 0x46, 0xfa, 0x56, 0x60, 0x46, 0x2e, 0xfb, 0x83,
	0xa9, 0x07, 0x66, 0xd5, 0x96, 0xbe, 0x1d, 0x90, 0x88, 0x30, 0x35, 0xaa, 0xb4, 0xb5, 0xd8, 0xdc,
	0xa0, 0x3f, 0x0a, 0x48, 0x64, 0xb0, 0x0e, 0xd0, 0x7d, 0xb0, 0x65, 0x93, 0x37, 0xad, 0xf4, 0x9d,
	0x80, 0x44, 0x0e, 0xeb, 0x51, 0xf8, 0x09, 0x76, 0x96, 0x15, 0xf2, 0xaf, 0xe7, 0x28, 0xa5, 0x0a,
	0xb3, 0xd7, 0x97, 0x37, 0x54, 0xab, 0x9e, 0x0c, 0xfa, 0xfa, 0xf6, 0xc1, 0xfa, 0x91, 0x17, 0x2d,
	0xfa, 0x6e, 0x40, 0x22, 0xf3, 0x64, 0xc0, 0x3a, 0x78, 0xb4, 0x03, 0xd0, 0xa0, 0x6c, 0x32, 0xae,
	0x2c, 0xc2, 0x9f, 0x06, 0xd0, 0xb9, 0xc0, 0xbc, 0xc1, 0x7b, 0xf5, 0x3d, 0x03, 0x83, 0x97, 0xba,
	0xbb, 0xf1, 0x6c, 0x12, 0xff, 0x7d, 0x1a, 0x33, 0x78, 0x49, 0x3f, 0x80, 0x5b, 0xd6, 0x99, 0xf6,
	0x93, 0xbe, 0xa1, 0x1b, 0x78, 0x1e, 0xff, 0x6f, 0x13, 0x9f, 0xd7, 0x97, 0x5a, 0x93, 0x54, 0x8d,
	0xd8, 0x32, 0xa7, 0xec, 0x21, 0x9d, 0x81, 0x7d, 0xc3, 0x45, 0xdd, 0x4a, 0x9d, 0x79, 0x77, 0x36,
	0x7d, 0xe8, 0xcf, 0x73, 0xad, 0x60, 0xbd, 0x72, 0xfa, 0x1e, 0x26, 0xf7, 0xec, 0x54, 0x8d, 0xdf,
	0xb1, 0xbb, 0x60, 0x93, 0xa9, 0x51, 0xd5, 0xd8, 0xad, 0x6c, 0x74, 0x97, 0xae, 0xc1, 0x3b, 0xe3,
	0x2d, 0x09, 0xbf, 0x80, 0xdd, 0xd9, 0xd1, 0x09, 0xb8, 0x17, 0x8b, 0xd3, 0xcb, 0x84, 0xa5, 0x87,
	0x67, 0xde, 0x80, 0x8e, 0xc0, 0xbc, 0x4a, 0x8e, 0x3c, 0x42, 0x01, 0xec, 0xd3, 0xf3, 0xc3, 0x8f,
	0x49, 0xea, 0x19, 0xd4, 0x05, 0xeb, 0x6c, 0x39, 0x3f, 0x3c, 0xf3, 0x4c, 0xea, 0xc0, 0x70, 0x91,
	0x5c, 0xa5, 0xde, 0x90, 0xee, 0x80, 0xb3, 0x62, 0xcb, 0xe3, 0x8b, 0xf9, 0xe7, 0xd4, 0xb3, 0x94,
	0xe4, 0xf2, 0xf4, 0x38, 0x59, 0x7a, 0x76, 0xf8, 0x12, 0xbc, 0x7b, 0xe9, 0xeb, 0x62, 0x4b, 0x9f,
	0x82, 0xa3, 0x1f, 0x7a, 0x56, 0xf1, 0xfe, 0x05, 0x8e, 0x34, 0x5e, 0xf0, 0xd9, 0x31, 0xc0, 0x09,
	0x16, 0x05, 0xbf, 0xe2, 0xa2, 0x58, 0xd3, 0x37, 0xe0, 0xa4, 0xf9, 0x56, 0x13, 0xf4, 0xc9, 0x03,
	0x2d, 0x4c, 0x1f, 0xc7, 0xff, 0x9a, 0x87, 0x83, 0x57, 0xe4, 0xda, 0xd6, 0x5f, 0xd0, 0xeb, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xbe, 0x5f, 0xc5, 0x50, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloWorldClient is the client API for HelloWorld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloWorldClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (HelloWorld_SayHelloClient, error)
}

type helloWorldClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloWorldClient(cc grpc.ClientConnInterface) HelloWorldClient {
	return &helloWorldClient{cc}
}

func (c *helloWorldClient) SayHello(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (HelloWorld_SayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloWorld_serviceDesc.Streams[0], "/HelloWorld/SayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloWorldSayHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HelloWorld_SayHelloClient interface {
	Recv() (*CreateOrderReply, error)
	grpc.ClientStream
}

type helloWorldSayHelloClient struct {
	grpc.ClientStream
}

func (x *helloWorldSayHelloClient) Recv() (*CreateOrderReply, error) {
	m := new(CreateOrderReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloWorldServer is the server API for HelloWorld service.
type HelloWorldServer interface {
	// Sends a greeting
	SayHello(*CreateOrderRequest, HelloWorld_SayHelloServer) error
}

// UnimplementedHelloWorldServer can be embedded to have forward compatible implementations.
type UnimplementedHelloWorldServer struct {
}

func (*UnimplementedHelloWorldServer) SayHello(req *CreateOrderRequest, srv HelloWorld_SayHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterHelloWorldServer(s *grpc.Server, srv HelloWorldServer) {
	s.RegisterService(&_HelloWorld_serviceDesc, srv)
}

func _HelloWorld_SayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateOrderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloWorldServer).SayHello(m, &helloWorldSayHelloServer{stream})
}

type HelloWorld_SayHelloServer interface {
	Send(*CreateOrderReply) error
	grpc.ServerStream
}

type helloWorldSayHelloServer struct {
	grpc.ServerStream
}

func (x *helloWorldSayHelloServer) Send(m *CreateOrderReply) error {
	return x.ServerStream.SendMsg(m)
}

var _HelloWorld_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HelloWorld",
	HandlerType: (*HelloWorldServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHello",
			Handler:       _HelloWorld_SayHello_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order.proto",
}
